kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-077c4031ef32dfc35
  directoryPerms: "700"
  basePath: "/roboshop" # optional